name: 🐞 Bug Report
description: Report a bug/issue to help improve the project.
title: "[Bug]: <write a concise title about the bug here>"
labels: ["bug", "triage"]
body:
    - type: checkboxes
      id: no-duplicate-issues
      attributes:
          label: Is there an existing issue for this?
          description: Please search to see if an issue already exists for the bug you encountered.
          options:
              - label:
                    I have searched the existing
                    [issues](https://github.com/trvswgnr/sloth-pipe/issues)
                required: true
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com
      validations:
          required: false
    - type: textarea
      id: current-behavior
      attributes:
          label: Current Behavior
          description: A concise description of what you're experiencing.
      validations:
          required: true
    - type: textarea
      id: expected-behavior
      attributes:
          label: Expected Behavior
          description: A concise description of what you expected to happen.
      validations:
          required: false
    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior.
          placeholder: |
              1. In this environment...
              2. With this config...
              3. Run '...'
              4. See error...
      validations:
          required: false
    - type: textarea
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
    - type: input
      id: version
      attributes:
          label: Version
          description: What version of our package are you running?
          placeholder: ex. 0.0.7
      validations:
          required: true
    - type: dropdown
      id: browsers
      attributes:
          label: "What browsers are you seeing the problem on?"
          multiple: true
          options:
              - Chrome
              - Firefox
              - Safari
              - Microsoft Edge
              - Brave
              - Opera
              - Other
      validations:
          required: false
    - type: checkboxes
      id: willing-to-work
      attributes:
          label: "Are you willing to work on this issue?"
          options:
              - label: "Yes I am. (leave this unchecked for No)"
                required: false
